const express = require("express");
const PORT = process.env.PORT || 4100;
const socketio = require("socket.io");
const http = require("http");
const app = express();
const router = require("./router");
const server = http.createServer(app);
const io = socketio(server);
app.use(router);
server.listen(PORT, () => console.log(`server has started on port ${PORT}`));
